import type { Product, ProductImage } from "../types";

const cover = (bg: string, fg: string, motif: "band" | "circle" | "rule"): ProductImage => ({ kind: "cover", bg, fg, motif });

interface BookInput {
  id: string; name: string; author: string; price: number; pages: number;
  genres: string[]; tags: string[]; gore: number; genreLabel: string;
  blurb: string; why: string; whyFor?: Record<string, string>; image: ProductImage;
}

const book = (b: BookInput): Product => ({
  id: b.id, store: "books", name: b.name, byline: b.author, price: b.price,
  blurb: b.blurb, why: b.why, whyFor: b.whyFor, image: b.image,
  attrs: { author: b.author, pages: b.pages, genres: b.genres, tags: b.tags, gore: b.gore, giftable: true },
  specs: [
    { label: "Pages", value: String(b.pages) },
    { label: "Genre", value: b.genreLabel },
    { label: "Format", value: "Paperback" },
  ],
});

export const BOOKS: Product[] = [
  book({ id: "b-harbour-lights", name: "The Harbour Lights", author: "Fiona Castellan", price: 16.99, pages: 352,
    genres: ["mystery", "police-procedural"], tags: ["gripping"], gore: 1, genreLabel: "Police procedural",
    blurb: "A body in the Leith docks, a detective three weeks from retirement, and a city that would rather forget.",
    why: "A weary Leith detective with Rebus's stubbornness and better manners.",
    whyFor: { procedural: "352 pages and a weary Leith detective with Rebus's stubbornness — Rankin territory he hasn't read yet, without the gore." },
    image: cover("#1F3A4A", "#F2E6D0", "band") }),
  book({ id: "b-quiet-ledger", name: "A Quiet Ledger", author: "Tom Aldous", price: 14.99, pages: 298,
    genres: ["mystery", "police-procedural"], tags: ["gripping"], gore: 0, genreLabel: "Police procedural",
    blurb: "An accountant vanishes the week before an audit. DS Nadia Kerr follows the money into the Borders.",
    why: "Fraud, not blood: a procedural that runs on paperwork and nerve.",
    whyFor: { procedural: "298 pages of fraud, not blood — a procedural that grips through paperwork and nerve." },
    image: cover("#E8DCC4", "#2B2B2B", "rule") }),
  book({ id: "b-north-wind", name: "North Wind, Late", author: "Morag Ellis", price: 17.99, pages: 384,
    genres: ["mystery", "police-procedural"], tags: ["gripping"], gore: 1, genreLabel: "Police procedural",
    blurb: "One DI, one Highland village, one winter — and nobody willing to say what happened at the ferry.",
    why: "Tight, tense and atmospheric, with a lead he'll want to follow into a series.",
    whyFor: { procedural: "384 pages, tense and atmospheric, with a DI he'll want to follow into a series — and the violence stays off the page." },
    image: cover("#3C4F3A", "#EDE6D6", "circle") }),
  book({ id: "b-cut-deep", name: "Cut Deep", author: "Declan Rourke", price: 12.99, pages: 336,
    genres: ["mystery", "police-procedural"], tags: ["gripping"], gore: 3, genreLabel: "Police procedural",
    blurb: "A Glasgow killer who leaves messages. Relentless and very graphic.",
    why: "Brilliantly paced, but it doesn't look away from the violence.", image: cover("#111111", "#D7263D", "band") }),
  book({ id: "b-long-watch", name: "The Long Watch", author: "Anneliese Moor", price: 19.99, pages: 544,
    genres: ["mystery", "police-procedural"], tags: ["gripping"], gore: 1, genreLabel: "Police procedural",
    blurb: "Twenty years, three detectives, one unsolved case — a sweeping, doorstop procedural.",
    why: "Rich and absorbing, if he has the time for a big one.", image: cover("#5B3A29", "#F4E9D8", "rule") }),
  book({ id: "b-glass-fjord", name: "Glass Fjord", author: "Sigrid Holm", price: 15.99, pages: 412,
    genres: ["mystery", "nordic"], tags: ["gripping"], gore: 3, genreLabel: "Nordic noir",
    blurb: "Bergen in the dark months, a string of ritual killings, and a detective who can't sleep.",
    why: "Classic Nordic noir — bleak, gripping and gruesome.", image: cover("#CFE0E8", "#16323F", "circle") }),
  book({ id: "b-ninth-winter", name: "The Ninth Winter", author: "Per Lindqvist", price: 16.49, pages: 368,
    genres: ["mystery", "nordic"], tags: ["gripping"], gore: 1, genreLabel: "Nordic noir",
    blurb: "A missing ferryman on a frozen archipelago; an inspector who knows every family on every island.",
    why: "Nordic atmosphere without the gore — quiet menace instead.",
    whyFor: { nordic: "368 pages of Nordic atmosphere, with quiet menace instead of gore." },
    image: cover("#E9EEF0", "#27414D", "band") }),
  book({ id: "b-pennyfold", name: "Murder at Pennyfold", author: "Hattie Blake", price: 10.99, pages: 288,
    genres: ["mystery", "cosy"], tags: ["charming"], gore: 0, genreLabel: "Cosy mystery",
    blurb: "A retired headmistress, a village fête and a poisoned Victoria sponge.",
    why: "Warm and clever — more charming than edge-of-the-seat.", image: cover("#F3D9C9", "#6B2D2D", "circle") }),
  book({ id: "b-ash-and-ink", name: "Ash & Ink", author: "Laurence Vey", price: 17.49, pages: 376,
    genres: ["mystery", "historical"], tags: ["gripping"], gore: 1, genreLabel: "Historical mystery",
    blurb: "Edinburgh, 1724: a printer's apprentice finds a confession set in type that nobody admits to writing.",
    why: "Rankin's city, three centuries earlier — a real page-turner.",
    whyFor: { historical: "376 pages — Rankin's Edinburgh three centuries earlier, and a real page-turner without the gore." },
    image: cover("#2E2A24", "#E3C77A", "rule") }),
  book({ id: "b-assayers-daughter", name: "The Assayer's Daughter", author: "Cora Winslow", price: 18.99, pages: 402,
    genres: ["mystery", "historical"], tags: ["slow-burn"], gore: 0, genreLabel: "Historical mystery",
    blurb: "A silver mine, a forged hallmark and a daughter who knows metal better than her father did.",
    why: "Beautifully written and patient — a slow burn.", image: cover("#D8D2C4", "#3A3A3A", "band") }),
  book({ id: "b-fire-and-salt", name: "Fire & Salt", author: "Idris Maddox", price: 16.99, pages: 392,
    genres: ["historical", "thriller", "history"], tags: ["gripping"], gore: 1, genreLabel: "Historical thriller",
    blurb: "Leith, 1645: plague, smugglers and a customs officer with one week to find a missing cargo.",
    why: "Bridges both worlds — all the tension of crime, rooted in real history.",
    whyFor: { history: "392 pages that bridge both worlds — the tension of crime he's always liked, rooted in the real history he's into now." },
    image: cover("#7A2E2E", "#F6EBDD", "band") }),
  book({ id: "b-cartographer", name: "The Cartographer's War", author: "Edmund Hale", price: 20.0, pages: 336,
    genres: ["history", "narrative-history"], tags: ["gripping"], gore: 1, genreLabel: "Narrative history",
    blurb: "After 1745, a handful of surveyors raced to map the Highlands — and changed Scotland for ever.",
    why: "True story, told like a thriller — chases, betrayals, deadlines.",
    whyFor: { history: "336 pages, true story, reads like a thriller — the history angle you said he's into now." },
    image: cover("#E4D6B8", "#23412F", "rule") }),
  book({ id: "b-last-signal", name: "The Last Signal", author: "Ruth Aberdeen", price: 18.99, pages: 304,
    genres: ["history", "narrative-history"], tags: ["gripping"], gore: 0, genreLabel: "Narrative history",
    blurb: "The wireless operators of wartime Orkney, and the message that nearly didn't get through.",
    why: "Codebreaking and suspense — he'll race through it.",
    whyFor: { history: "304 pages of wartime codebreaking and suspense — real history that moves like a thriller." },
    image: cover("#1D2B3A", "#F0C987", "circle") }),
  book({ id: "b-iron-road", name: "Iron Road", author: "Callum Firth", price: 19.99, pages: 368,
    genres: ["history", "narrative-history"], tags: ["gripping"], gore: 1, genreLabel: "Narrative history",
    blurb: "How the railways remade Scotland — engineers, swindlers and the bridge that fell.",
    why: "Big characters and real stakes; history with momentum.",
    whyFor: { history: "368 pages of engineers, swindlers and a bridge that fell — history with the momentum he wants." },
    image: cover("#3B3B3B", "#E9A23B", "band") }),
  book({ id: "b-empire-of-tides", name: "Empire of Tides", author: "Margaret Olufsen", price: 28.0, pages: 688,
    genres: ["history"], tags: ["gripping"], gore: 1, genreLabel: "History",
    blurb: "Five hundred years of the North Sea, from herring fleets to oil rigs.",
    why: "Magnificent — and very long.", image: cover("#0F3D4C", "#E6F0F2", "rule") }),
  book({ id: "b-quiet-centuries", name: "The Quiet Centuries", author: "Henry Aske", price: 17.99, pages: 320,
    genres: ["history"], tags: ["reflective"], gore: 0, genreLabel: "History",
    blurb: "A gentle history of Scottish parish life, 1600–1900.",
    why: "Thoughtful and lovely, but more reflective than gripping.", image: cover("#EDE3CF", "#4A4034", "circle") }),
  book({ id: "b-bones-of-culloden", name: "The Bones of Culloden", author: "Alasdair Grant", price: 19.49, pages: 352,
    genres: ["history"], tags: ["gripping"], gore: 3, genreLabel: "History",
    blurb: "A forensic, unflinching account of the battle and its aftermath.",
    why: "Gripping, but graphic about the battlefield.", image: cover("#2B1D1D", "#C9B79C", "band") }),
  book({ id: "b-small-hours", name: "The Small Hours", author: "Nina Achterberg", price: 13.99, pages: 240,
    genres: ["literary"], tags: ["reflective"], gore: 0, genreLabel: "Literary fiction",
    blurb: "A night-shift nurse, a city asleep, and the patients who can't.",
    why: "Quietly devastating literary fiction.", image: cover("#F2EEE8", "#333333", "rule") }),
];
